version: "3.7"
services:
  webapp:
    build: .
    ports:
      - 5001:5001
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password